// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;

import edu.wpi.first.wpilibj.command.PIDCommand;

import org.usfirst.frc5122.Fred2.Robot;
import org.usfirst.frc5122.Fred2.RobotMap;
import org.usfirst.frc5122.Fred2.U;

/**
 *
 */
public class  a_drive_move_dist extends PIDCommand {

	private double distance;
	private final double THRESH = 2;
	private double maxspeed = .5;
    public a_drive_move_dist(double distance) {
    	//super("a_drive_move_dist", 0.051, 0.0005, .5, 0.02);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("a_drive_move_dist", 0.11, 0.0, 0.0, 0.02);
        getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        this.distance = distance;

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        System.out.println("Creating a_drive_move_dist("+distance+")");
    }
    public a_drive_move_dist(double distance, double maxspeed) {
    	this(distance);
    	this.maxspeed = maxspeed;
    }
    

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
    	System.out.println("PIDGET: "+RobotMap.driveLeftEncoder.pidGet());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return RobotMap.driveLeftEncoder.pidGet();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	output = U.constrain(-maxspeed, output, maxspeed);
    	Robot.drive.HDrive(-output, 0, 0);
    	System.out.println("PIDOUT: "+output);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	RobotMap.driveLeftEncoder.reset();
    	getPIDController().setSetpoint(distance);
    	getPIDController().enable();
    	System.out.println("INIT "+U.className(this));
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.println("EXEC a_drive_move_dist");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("ERROR: "+getPIDController().getError());
    	return getPIDController().getError() <= THRESH;
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("END");
    	getPIDController().disable();
    	Robot.drive.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("INT");
    	end();
    }
}
