// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;

import edu.wpi.first.wpilibj.command.PIDCommand;

import org.usfirst.frc5122.Fred2.Robot;
import org.usfirst.frc5122.Fred2.RobotMap;
import org.usfirst.frc5122.Fred2.U;

/**
 *
 */
public class  a_drive_turn_enc extends PIDCommand {
	private double angle, max;
    public a_drive_turn_enc(double angle, double kp, double ki, double kd, double max) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("a_drive_turn_enc", 1.0, 0.0, 0.0, 0.02);
        getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        this.angle = angle;
        this.max = max;

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
    	double out = Robot.drive.getDegreesFromEncoderValues();
    	System.out.println("DEG: "+out);
        return out;
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	
    	output = U.constrain(-max, output, max);
    	if (Math.abs(output) < .4 && output != 0) {
    		output = (output/Math.abs(output))*.4;
    	}
    	System.out.println("OUT: "+output);
//    	if (rampUP)
//    	{
//	    	if ((timeSinceInitialized()*2+.4)<1) {
//	    		output = output * (timeSinceInitialized()*2+.4);
//	    	}
//	    }

        Robot.drive.HDrive(0, -output, 0);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	setSetpoint(angle);
    	getPIDController().enable();
    	Robot.drive.resetLeftDistance();
    	Robot.drive.ResetRightDistance();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("ERR: "+Math.abs(getPIDController().getError()));
    	return Math.abs(getPIDController().getError()) <= 1.5;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.stop();
    	getPIDController().disable();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
