// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;

import org.usfirst.frc5122.Fred2.Robot;
import org.usfirst.frc5122.Fred2.RobotMap;
import org.usfirst.frc5122.Fred2.U;

import edu.wpi.first.wpilibj.command.PIDCommand;

/**
 *
 */
public class  a_drive_strafe_dist extends PIDCommand {
	
	private double distance;
	private final double THRESH = 2;
	private double maxspeed = .5;
	public a_drive_strafe_dist(double distance) {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("a_drive_strafe_dist", 1.0, 0.0, 0.0, 0.02);
        getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        this.distance = distance;

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        System.out.println("Creating a_drive_strafe_dist("+distance+")");
    }
	public a_drive_strafe_dist(double distance, double maxspeed) {
    	this(distance);
    	this.maxspeed = maxspeed;
    }
	    

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
    	System.out.println("PIDGET: "+RobotMap.driveHdriveEncoder.pidGet());

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return RobotMap.driveHdriveEncoder.pidGet();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	output = U.constrain(-maxspeed, output, maxspeed);
    	Robot.drive.HDrive(0, 0, -output);
    	System.out.println("PIDOUT: "+output);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	RobotMap.driveHdriveEncoder.reset();
    	getPIDController().setSetpoint(distance);
    	getPIDController().enable();
    	System.out.println("INIT "+U.className(this));
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.println("EXEC a_drive.strafe_dist");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	System.out.println("ERROR: "+getPIDController().getError());
    	return getPIDController().getError() <= THRESH;
    }

    // Called once after isFinished returns true
    protected void end() {
    	System.out.println("END");
    	getPIDController().disable();
    	Robot.drive.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("INT");
    	end();
    }
}
