// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;

import org.usfirst.frc5122.Fred2.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class  a_drive_move_time extends Command {

	private double duration;
	private double speed;
	private double starting;
	
    public a_drive_move_time(double duration, double speed) {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	this.duration = duration;
    	this.speed = speed;

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	starting = timeSinceInitialized();
    	System.out.println("INIT a_drive_move_time");
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.drive.HDrive(-speed, 0, 0);
    	System.out.println("EXEC a_drive_move_time ");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	boolean done = timeSinceInitialized() >  (starting+duration);
    	System.out.println("IsFini "+done);
        return done;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.drive.stop();
    	System.out.println("END a_drive_move_time ");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	System.out.println("INT");
    	end();
    }
}
