// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class auto_3totes extends CommandGroup {
    
    public  auto_3totes() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	addSequential(new a_debug("Starting"));
    	addSequential(new a_drive_move_time(.25, .5));
    	addSequential(new a_debug("----1----"));
    	addSequential(new a_grabber_ungrab());
    	addSequential(new a_debug("----2----"));
    	addSequential(new a_lift_bottom());
    	addSequential(new a_debug("----3----"));
    	addSequential(new a_grabber_grab());
    	addSequential(new a_debug("----4----"));
    	addParallel(new a_lift_move_time(2.5, 1));
    	addSequential(new a_debug("----5----"));
    	//we have picked up a tote
    	addSequential(new a_drive_turn_angle(45), 2.5);
    	addSequential(new a_debug("----6----"));
    	addSequential(new a_drive_move_dist(40), 1.5);
    	addSequential(new a_debug("----7----"));
    	addSequential(new a_drive_turn_angle(-45), 2.5);
    	addSequential(new a_debug("----8----"));
    	// now we are parallel to recycling container
    	addSequential(new a_drive_move_dist(15));
    	addSequential(new a_debug("----9----"));
    	addSequential(new a_drive_turn_angle(-45), 2.5);
    	addSequential(new a_debug("----10----"));
    	addSequential(new a_drive_move_dist(35));
    	addSequential(new a_debug("----11----"));
    	addSequential(new a_drive_turn_angle(45), 2.5);
    	addSequential(new a_debug("----Done----"));
    	//Should be ready to pickup the next tote
    	
    	
    }
}
