// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class auto_rc_totenm3 extends CommandGroup {
    
    public  auto_rc_totenm3() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	double driveSpeed = .8;
    	double liftSpeed = .75;
    	double turnSpeed = .65;
    	addSequential(new a_lift_move_dist(26, liftSpeed));		// pickup recycling container
    	addSequential(new a_drive_move_dist(25, .6));			//drive
//    	addSequential(new a_drive_turn_angle(10, .65, false),1); //correct driving
    	addSequential(new a_drive_move_time(.25, .7));
    	addSequential(new a_lift_bottom());						//pickup tote
    	
    	addSequential(new a_lift_move_dist(2, liftSpeed)); 		//lift up
    	
    	addSequential(new a_drive_turn_angle(75, .65), 1.5);
    	addSequential(new a_drive_move_dist(-120, driveSpeed));
    	addSequential(new a_drive_turn_angle(-90, .65), 2);
    	//addSequential(new a_drive_move_dist(-80, driveSpeed));
    }
}
