// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class auto_3totes_norc extends CommandGroup {
    
    public  auto_3totes_norc() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
    	
    	
    	
    	addParallel(new a_lift_move_dist(17));
    	addSequential(new WaitCommand("Wait for partners", 2.5));
    	addSequential(new a_drive_move_dist_straight(90, .75));
    	addSequential(new a_grabber_ungrab());
//    	addSequential(new a_drive_move_time_straight(1.5, .8));
//    	addSequential(new a_drive_move_time_straight(.5, .65));
    	addSequential(new a_lift_bottom());//pickup tote 2
    	addSequential(new a_grabber_grab());
//    	addSequential(new WaitCommand(1));
    	addSequential(new a_drive_move_time(.25, .8));
    	addParallel(new a_lift_move_dist(18)); //lift up
    	addSequential(new a_drive_move_dist_straight(82, .75));
//    	addSequential(new a_drive_move_time_straight(1.5, .8));
//    	addSequential(new a_drive_move_time_straight(.5, .65));\
    	addSequential(new a_grabber_ungrab());
    	addSequential(new a_lift_bottom());//pickup tote 3
    	addSequential(new a_grabber_grab());
    	addSequential(new a_drive_move_time(.25, .8));
    	
    	addSequential(new a_drive_turn_angle(55));
    	addParallel(new a_grabber_push());
    	addSequential(new a_drive_move_dist_straight(120));
    	
    	addSequential(new a_drive_move_dist_straight(-10));
    	

    }
}
