// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc5122.Fred2.Robot;

/**
 *
 */
public class  oi_Lift extends Command {
	
	private final double DEADBAND = .05;

    public oi_Lift() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (Robot.oi.getXbox().getRightTrigger() > DEADBAND || Robot.oi.getXbox().isRB()) {
    		Robot.lift.moveLift(-Robot.oi.getXbox().getRightTrigger());
    	} else if (Robot.oi.getXbox().getLeftTrigger() > DEADBAND || Robot.oi.getXbox().isLB()) {
    		System.out.println("right");
    		Robot.lift.moveLift(Robot.oi.getXbox().getLeftTrigger());
    	} else {
    		Robot.lift.moveLift(0);
    	}
    	if ((Robot.oi.getXbox().getRightStickY()*-1) > DEADBAND || Robot.oi.getXbox().isA()) {
    		Robot.lift.push();
    	} else {
    		Robot.lift.unpush();
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lift.moveLift(0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
