// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.subsystems;

import org.usfirst.frc5122.Fred2.RobotMap;
import org.usfirst.frc5122.Fred2.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class CanGrabber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput topLimit = RobotMap.canGrabberTopLimit;
    DigitalInput bottomLimit = RobotMap.canGrabberBottomLimit;
    SpeedController reel = RobotMap.canGrabberReel;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void set(double speed) {
    	System.out.println("Going "+speed+" top?"+isAtTop()+" bot?"+isAtBottom());
    	if (isAtTop()) //at top
    	{
    		//only go down
    		if(speed < 0) {
    			go(speed);
    		} else {
    			go(0);
    		}
    	} 
    	else if(isAtBottom()) //at bottom 
    	{
    		//only go up
    		if(speed > 0) {
    			go(speed);
    		} else {
    			go(0);
    		}
    	}
    	else
    	{
    		//go anyway
    		go(speed);
    	}
    }
    //UNSAFE METHOD, DOES NOT CHECK LIMIT SWITCHES! -- DO NOT USE
    private void go(double speed) {
    	reel.set(speed);
    }
    public void stop() {
    	go(0);
    }
    
    public boolean isAtTop() {
    	//System.out.println("State: " + topLimit.get());
    	return topLimit.get();
    }
    public boolean isAtBottom() {
    	return false; //bottomLimit.get();
    }
}

