// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2.subsystems;

import org.usfirst.frc5122.Fred2.RobotMap;
import org.usfirst.frc5122.Fred2.commands.oi_Lift;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Lift extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController lift = RobotMap.liftLift;
    DigitalInput topLimit = RobotMap.liftTopLimit;
    DigitalInput bottomLimit = RobotMap.liftBottomLimit;
    SpeedController liftCim = RobotMap.liftLiftCim;
    Encoder liftEncoder = RobotMap.liftLiftEncoder;
    DoubleSolenoid stabilizer = RobotMap.liftStabilizer;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    boolean pinched = false;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new oi_Lift());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
		
		
		

    
    public void moveLift(double speed) {
    	if(topLimit.get()) {
    		//only go down
    		if(speed < 0) {
    			go(speed);
    			
    		} else {
    			go(0);
    		}
    	} else if(bottomLimit.get()) {
    		//only go up
    		if(speed > 0) {
    			go(speed);
    		} else {
    			go(0);
    		}
    	} else {
    		go(speed);
    	}
    }
    //UNSAFE METHOD, DOES NOT CHECK LIMIT SWITCHES!
    private void go(double speed) {
    	if (Math.abs(speed) < .4 && speed != 0) {
    		speed = (speed/Math.abs(speed))*.4;
    	}
//    	lift.set(speed);
    	liftCim.set(speed);
    	//if(speed>0){
    		//greenLiftLights.set(true);
    		//blueLiftLights.set(false);
    		//redLiftLights.set(false);
    	//} else if(speed <0){
    		//greenLiftLights.set(false);
    		//blueLiftLights.set(true);
    		//redLiftLights.set(false);
    	//} else {
    		//greenLiftLights.set(false);
    		//blueLiftLights.set(false);
    		//redLiftLights.set(true);
    	//}
    		
    		
    		
    	
    }
    public void stop() {
    	moveLift(0);
    }
    
    public boolean isAtTop() {
    	return topLimit.get();
    }
    public boolean isAtBottom() {
    	return bottomLimit.get();
    }
 
    public double getDistance() {
    	return liftEncoder.getDistance();
    }
    public void reset() {
    	liftEncoder.reset();
    }
    
    public void rcGrab(boolean pinch) {
    	if (pinch) {
    		stabilizer.set(DoubleSolenoid.Value.kForward);
    	} else {
    		stabilizer.set(DoubleSolenoid.Value.kReverse);
    	}
    	pinched = pinch;
    }
    public void rcGrab() {
    	rcGrab(false);
    }
    public void rcUngrab() {
    	rcGrab(true);
    }
    
    public void pinchToggle() {
    	rcGrab(!pinched);
    }
    
}

