// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "a_drive_move_stra.h"

a_drive_move_stra::a_drive_move_stra() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drive);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void a_drive_move_stra::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void a_drive_move_stra::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool a_drive_move_stra::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void a_drive_move_stra::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void a_drive_move_stra::Interrupted() {

}
