// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "oi_Stabilizer.h"

oi_Stabilizer::oi_Stabilizer() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void oi_Stabilizer::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void oi_Stabilizer::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool oi_Stabilizer::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void oi_Stabilizer::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void oi_Stabilizer::Interrupted() {

}
