// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/a_cangrabber_deploy.h"
#include "Commands/a_cangrabber_retract.h"
#include "Commands/a_debug.h"
#include "Commands/a_drive_move_dist.h"
#include "Commands/a_drive_move_dist_straight.h"
#include "Commands/a_drive_move_stra.h"
#include "Commands/a_drive_move_time.h"
#include "Commands/a_drive_move_time_straight.h"
#include "Commands/a_drive_turn_angle.h"
#include "Commands/a_drive_turn_angle1.h"
#include "Commands/a_grabber_grab.h"
#include "Commands/a_grabber_push.h"
#include "Commands/a_grabber_ungrab.h"
#include "Commands/a_lift_bottom.h"
#include "Commands/a_lift_move_dist.h"
#include "Commands/a_lift_move_time.h"
#include "Commands/a_lift_setup.h"
#include "Commands/a_lift_top.h"
#include "Commands/auto_1rc_bump.h"
#include "Commands/auto_1tote_bump.h"
#include "Commands/auto_1tote_pos1.h"
#include "Commands/auto_1tote_pos1_lm2.h"
#include "Commands/auto_1tote_pos2.h"
#include "Commands/auto_1tote_pos3.h"
#include "Commands/auto_2tote_pos1.h"
#include "Commands/auto_3totes.h"
#include "Commands/auto_3totes_norc.h"
#include "Commands/auto_canGraabber.h"
#include "Commands/auto_liftup.h"
#include "Commands/auto_liftup_2.h"
#include "Commands/auto_robotset.h"
#include "Commands/b_zero_yaw.h"
#include "Commands/oi_Grabber.h"
#include "Commands/oi_HDrive.h"
#include "Commands/oi_Lift.h"
#include "Commands/oi_Stabilizer.h"
#include "Commands/oi_cangrabber_down.h"
#include "Commands/oi_cangrabber_up.h"
#include "Commands/oi_containerUprighter.h"
#include "Commands/sd_drive_turn_angle.h"
#include "Commands/sd_lift_dist.h"
#include "Commands/sd_move_dist.h"
#include "Commands/sd_strafe_dist.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	aux = new Joystick(1);
	
	driver = new Joystick(0);
	
	canGrabberDown = new JoystickButton(driver, 9);
	canGrabberDown->WhileHeld(new oi_cangrabber_down());
	canGrabberUp = new JoystickButton(driver, 10);
	canGrabberUp->WhileHeld(new oi_cangrabber_up());
	stabilizer = new JoystickButton(driver, 4);
	stabilizer->WhenPressed(new oi_Stabilizer());
	containerUprighter = new JoystickButton(driver, 3);
	containerUprighter->WhenPressed(new oi_containerUprighter());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("b_zero_yaw", new b_zero_yaw());

	SmartDashboard::PutData("oi_cangrabber_up", new oi_cangrabber_up());

	SmartDashboard::PutData("oi_cangrabber_down", new oi_cangrabber_down());

	SmartDashboard::PutData("a_cangrabber_deploy", new a_cangrabber_deploy());

	SmartDashboard::PutData("a_cangrabber_retract", new a_cangrabber_retract());

	SmartDashboard::PutData("auto_canGraabber", new auto_canGraabber());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getAux() {
	return aux;
}

Joystick* OI::getDriver() {
	return driver;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
