// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5122.Fred2;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveLeftFront;
    public static SpeedController driveLeftRear;
    public static SpeedController driveRightFront;
    public static SpeedController driveRightRear;
    public static RobotDrive driveDrivetrain;
    public static SpeedController driveStrafe;
    public static Gyro drivegyro;
    public static DoubleSolenoid liftPusher;
    public static SpeedController liftLift;
    public static DigitalInput liftTopLimit;
    public static DigitalInput liftBottomLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftFront = new Talon(0);
        LiveWindow.addActuator("Drive", "LeftFront", (Talon) driveLeftFront);
        
        driveLeftRear = new Talon(1);
        LiveWindow.addActuator("Drive", "LeftRear", (Talon) driveLeftRear);
        
        driveRightFront = new Talon(2);
        LiveWindow.addActuator("Drive", "RightFront", (Talon) driveRightFront);
        
        driveRightRear = new Talon(3);
        LiveWindow.addActuator("Drive", "RightRear", (Talon) driveRightRear);
        
        driveDrivetrain = new RobotDrive(driveLeftFront, driveLeftRear,
              driveRightFront, driveRightRear);
        
        driveDrivetrain.setSafetyEnabled(true);
        driveDrivetrain.setExpiration(0.1);
        driveDrivetrain.setSensitivity(0.5);
        driveDrivetrain.setMaxOutput(1.0);

        driveStrafe = new Talon(4);
        LiveWindow.addActuator("Drive", "Strafe", (Talon) driveStrafe);
        
        drivegyro = new Gyro(0);
        LiveWindow.addSensor("Drive", "gyro", drivegyro);
        drivegyro.setSensitivity(0.007);
        liftPusher = new DoubleSolenoid(0, 0, 1);      
        LiveWindow.addActuator("Lift", "Pusher", liftPusher);
        
        liftLift = new Talon(5);
        LiveWindow.addActuator("Lift", "Lift", (Talon) liftLift);
        
        liftTopLimit = new DigitalInput(4);
        LiveWindow.addSensor("Lift", "TopLimit", liftTopLimit);
        
        liftBottomLimit = new DigitalInput(5);
        LiveWindow.addSensor("Lift", "BottomLimit", liftBottomLimit);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
